server:
  port: 0

spring:
  application:
    name: rates-ms
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
          multiplier: 2
          max-interval: 300000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}